trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: intellivault-secrets
  - name: DOCKER_REGISTRY
    value: 'intellivaultacr.azurecr.io'
  - name: AKS_CLUSTER_NAME
    value: 'intellivault-aks'
  - name: AKS_RESOURCE_GROUP
    value: 'intellivault-rg'

stages:
  - stage: Build
    jobs:
      - job: BuildAndTest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
          
          - script: npm ci
            displayName: 'Install dependencies'
          
          - script: npm run build
            displayName: 'Build'
          
          - script: npm run test
            displayName: 'Run tests'
          
          - task: Docker@2
            inputs:
              command: buildAndPush
              containerRegistry: 'IntelliVaultACR'
              repository: 'services'
              tags: |
                $(Build.BuildId)
                latest

  - stage: Deploy
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeployToAKS
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  inputs:
                    action: deploy
                    kubernetesServiceConnection: 'intellivault-aks-connection'
                    namespace: intellivault
                    manifests: |
                      $(Pipeline.Workspace)/k8s/*.yaml
                    containers: |
                      $(DOCKER_REGISTRY)/document-service:$(Build.BuildId)
                      $(DOCKER_REGISTRY)/search-service:$(Build.BuildId)
                      $(DOCKER_REGISTRY)/analytics-service:$(Build.BuildId)