apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellivault-backend
  labels:
    app: intellivault-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: intellivault-backend
  template:
    metadata:
      labels:
        app: intellivault-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: intellivault/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: AZURE_COSMOS_DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: intellivault-config
              key: cosmos-endpoint
        - name: AZURE_COSMOS_DB_KEY
          valueFrom:
            secretKeyRef:
              name: intellivault-secrets
              key: cosmos-key
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            configMapKeyRef:
              name: intellivault-config
              key: storage-account-name
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: intellivault-secrets
              key: storage-account-key
        - name: AZURE_SEARCH_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: intellivault-config
              key: search-endpoint
        - name: AZURE_SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: intellivault-secrets
              key: search-api-key
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: intellivault-config
              key: openai-endpoint
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: intellivault-secrets
              key: openai-api-key
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: intellivault-config
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: intellivault-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: intellivault-registry-secret
