apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intellivault.fullname" . }}-frontend
  labels:
    {{- include "intellivault.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "intellivault.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "intellivault.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: frontend
        image: "{{ .Values.global.imageRegistry }}{{ .Values.frontendImage.registry }}/{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.frontendService.targetPort }}
          protocol: TCP
        env:
        - name: REACT_APP_API_URL
          value: {{ .Values.frontend.env.REACT_APP_API_URL | quote }}
        - name: REACT_APP_TENANT_ID
          value: {{ .Values.app.defaultTenantId | quote }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
