apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: intellivault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: intellivaultacr.azurecr.io/analytics-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_INSIGHTS_KEY
          valueFrom:
            secretKeyRef:
              name: intellivault-secrets
              key: app-insights-key
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: intellivault
spec:
  selector:
    app: analytics-service
  ports:
  - port: 80
    targetPort: 3002
  type: ClusterIP