apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: intellivault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: intellivaultacr.azurecr.io/search-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: AZURE_AI_SEARCH_KEY
          valueFrom:
            secretKeyRef:
              name: intellivault-secrets
              key: ai-search-key
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: intellivault
spec:
  selector:
    app: search-service
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP